services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
      - ./certs:/app/certs
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_replace_in_production
      - SSL_KEY_PATH=/app/certs/server.key
      - SSL_CERT_PATH=/app/certs/server.crt
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
